### ISSUE TITLE
Factory reset Hue bridge

### ISSUE THREAD

**Issue by technicalpickles** [technicalpickles/picklehome#10]
This is working towards https://github.com/technicalpickles/picklehome/issues/8 and https://github.com/technicalpickles/picklehome/issues/9 . To get there, I need my Echos to not automatically discover the Hue bridge, and thus all the lights, so homeassistant can manage them.

Hue bridges are "interesting" in that they keep old data around, even if it's not visible in the app. There's a "cleanup" option for that, but it doesn't seem to help.

**Comment by technicalpickles** [comment]
This is done. Here's the process I used:

- make sure all lights are on
- use a paperclip to press the the factory reset button
- in iOS app: Settings -> Light Setup -> Add (ie the + sign)
- go from room to room:
   - press the first light in the list, see if it blinks
   - if it is blinking, you found the light
   - rename the light, use previous name if possible to avoid breaking automation ([groups](https://github.com/technicalpickles/picklehome-homeassistant-config/blob/master/groups.yaml) is a good listing)

protip: this involves lights flashing, so don't do this when you might wake someone 👶

**Comment by technicalpickles** [comment]
The reset is done, but homeassistant isn't happy about it:

```
home-assistant_1  | 2017-11-23 01:29:16 ERROR (MainThread) [homeassistant.components.light] Error while setting
up platform hue
home-assistant_1  | Traceback (most recent call last):
home-assistant_1  |   File "/usr/src/app/homeassistant/helpers/entity_component.py", line 171, in _async_setup_p
latform
home-assistant_1  |     SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
home-assistant_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
home-assistant_1  |     return fut.result()
home-assistant_1  |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
home-assistant_1  |     raise self._exception
home-assistant_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
home-assistant_1  |     result = self.fn(*self.args, **self.kwargs)
home-assistant_1  |   File "/usr/src/app/homeassistant/components/light/hue.py", line 138, in setup_platform
home-assistant_1  |     allow_in_emulated_hue, allow_hue_groups)
home-assistant_1  |   File "/usr/src/app/homeassistant/components/light/hue.py", line 277, in setup_bridge
home-assistant_1  |     update_lights()
home-assistant_1  |   File "/usr/src/app/homeassistant/util/__init__.py", line 306, in wrapper
home-assistant_1  |     result = method(*args, **kwargs)
home-assistant_1  |   File "/usr/src/app/homeassistant/util/__init__.py", line 306, in wrapper
home-assistant_1  |     result = method(*args, **kwargs)
home-assistant_1  |   File "/usr/src/app/homeassistant/components/light/hue.py", line 192, in update_lights
home-assistant_1  |     api_lights = api.get('lights')
home-assistant_1  | AttributeError: 'list' object has no attribute 'get'
```

**Comment by technicalpickles** [comment]
I was able to fix this by removing the `phue.conf` in the homeassistant directory

**Comment by technicalpickles** [comment]
Keeping this open until I file an issue upstream.

**Comment by technicalpickles** [comment]
Filed https://github.com/home-assistant/home-assistant/issues/11133 for the upstream issue
